'use client'

import "./globals.css";
import { Nunito } from "next/font/google";
import NavBar from "./components/navbar/NavBar";
import RegisterModal from "./components/modals/RegisterModals";
import LoginModal from "./components/modals/LoginModals";
import RegisterUser from "./components/modals/RegisterUser";
import useRegisterModal from "./hooks/useRegisterModal";
import useLoginModal from "./hooks/useLoginModal";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const registerModal = useRegisterModal();
  const loginModal = useLoginModal();

  return (
    <html lang="en">
      <body className={inter.className}>
        <RegisterModal />
        <LoginModal />
        <RegisterUser />
        <NavBar />
        <main
          className={`z-5 ${
            registerModal.isOpen || loginModal.isOpen ? "fixed" : "relative"
          } top-[7vh] xl:top-[11.5vh]`}
        >
          {children}
          <div className="flex justify-center p-2">
            <p>© 2023 Vicky Gaming Community. All rights reserved.</p>
          </div>
        </main>
      </body>
    </html>
  );
}
